my_diffbot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Velocity Controllers ---------------------------------------
  joint1_Velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: left_wheel_joint
    pid: 
      p: 0.1
      i: 0.001 
      i_clamp: 0.01
  joint2_Velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: right_wheel_joint
    pid: 
      p: 0.1
      i: 0.001
      i_clamp: 0.01